# Generated by Django 5.0.1 on 2024-01-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone No')),
                ('instrument_type', models.CharField(max_length=50)),
            ],
        ),
    ]
